ya = Yuki::Animation
animation_user = Yuki::Animation::UserBankRelativeAnimation.new
# Psychic
animation_target = ya.wait(0.1)
animation_user.play_on_bank(0, ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'Psychic', :animation], [:set_rect, 0, 0, 256, 172], [:zoom=, 1.5], [:set_origin, 80, 171]))
animation_user.play_on_bank(1, ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'Psychic', :animation], [:set_rect, 0, 0, 256, 172], [:zoom=, 1.5], [:set_origin, 180, 124]))
main_t_anim = ya.resolved
animation_user.play_before(main_t_anim)
main_t_anim.play_before(ya.move_sprite_position(0, :sprite, :user, :user))
main_t_anim.play_before(ya.se_play('moves/Psychic'))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 256, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 256, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 256, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 256, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 256, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 256, 0, 256, 172))
main_t_anim.play_before(ya.wait(0.1))
animation_user.play_before(ya.dispose_sprite(:sprite))

Battle::MoveAnimation.register_specific_animation(:psychic, :first_use, animation_user, animation_target)
