ya = Yuki::Animation
# Facade
animation_target = ya.wait(0.1)
animation_user = ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'Facade', :animation], [:set_rect, 0, 0, 104, 192], [:zoom=, 0.75], [:set_origin, 52, 132])
main_t_anim = ya.resolved
animation_user.play_before(main_t_anim)
main_t_anim.play_before(ya.move_sprite_position(0, :sprite, :user, :user))
main_t_anim.play_before(ya.se_play('moves/Facade'))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 104, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 208, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 312, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 416, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 520, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 624, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 728, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 832, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 936, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1040, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1144, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1248, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1352, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1456, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1560, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1664, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1768, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.move_sprite_position(0, :sprite, :target, :target))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1872, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1976, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.085))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 2080, 0, 104, 192))
main_t_anim.play_before(ya.wait(0.1))
animation_user.play_before(ya.dispose_sprite(:sprite))

Battle::MoveAnimation.register_specific_animation(:facade, :first_use, animation_user, animation_target)
