ya = Yuki::Animation
animation_target = Yuki::Animation::UserBankRelativeAnimation.new
# DracoMeteor
animation_user = ya.wait(0.1)
animation_target.play_on_bank(0, ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'DracoMeteor_0', :animation], [:set_rect, 0, 0, 208, 192], [:zoom=, 1], [:set_origin, 104, 132]))
animation_target.play_on_bank(1, ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'DracoMeteor_1', :animation], [:set_rect, 0, 0, 208, 192], [:zoom=, 1], [:set_origin, 104, 132]))
main_t_anim = ya.resolved
animation_target.play_before(main_t_anim)
main_t_anim.play_before(ya.move_sprite_position(0, :sprite, :target, :target))
main_t_anim.play_before(ya.se_play('moves/DracoMeteor'))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.5))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 208, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 416, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 624, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 832, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 208, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 416, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 624, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 832, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 208, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 416, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 624, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 832, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 208, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 416, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 624, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 832, 0, 208, 192))
main_t_anim.play_before(ya.wait(0.16))
animation_target.play_before(ya.dispose_sprite(:sprite))

Battle::MoveAnimation.register_specific_animation(:draco_meteor, :first_use, animation_user, animation_target)
