ya = Yuki::Animation
animation_user = Yuki::Animation::UserBankRelativeAnimation.new
# SludgeWave
animation_target = ya.wait(0.1)
animation_user.play_on_bank(0, ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'SludgeWave_0', :animation], [:set_rect, 0, 0, 254, 150], [:zoom=, 1.55], [:set_origin, 127, 150]))
animation_user.play_on_bank(1, ya.create_sprite(:viewport, :sprite, Sprite, nil, [:load, 'SludgeWave_1', :animation], [:set_rect, 0, 0, 254, 150], [:zoom=, 1.55], [:set_origin, 170, 100]))
main_t_anim = ya.resolved
animation_user.play_before(main_t_anim)
main_t_anim.play_before(ya.move_sprite_position(0, :sprite, :user, :user))
main_t_anim.play_before(ya.se_play('moves/SludgeWave'))
main_t_anim.play_before(ya.wait(0.1))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 0, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 254, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 508, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 762, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1016, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1270, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1524, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.095))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 1778, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.8))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 2032, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 2286, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.15))
main_t_anim.play_before(ya.send_command_to(:sprite, :set_rect, 2540, 0, 254, 150))
main_t_anim.play_before(ya.wait(0.15))
animation_user.play_before(ya.dispose_sprite(:sprite))

Battle::MoveAnimation.register_specific_animation(:sludge_wave, :first_use, animation_user, animation_target)
